# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_cn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='wechat',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
